baseURL = "https://convective-heat-engine.github.io/"
googleAnalytics = "G-R8DF74XFGZ"
languageCode = "en-us"
title = "Convective Heat Engine"
theme = "book"

[params]
BookMenuBundle = "/menu"
BookSearch = false
